const assert=require('assert'),crypto=require('crypto');
exports['login creates independent PKCE challenges and browser bindings'] = ()=>{const {LoginTransactions}=require('../src/auth');const t=new LoginTransactions(),a=t.begin('/catalog'),b=t.begin('/create');assert.notStrictEqual(a.state,b.state);assert.notStrictEqual(a.binding,b.binding);assert.strictEqual(a.challenge,crypto.createHash('sha256').update(a.verifier).digest('base64url'));assert(a.nonce.length>=32);assert.throws(()=>t.begin('//outside.example'),/return/);};

exports['login callbacks reject tampering expiration and replay'] = ()=>{const {LoginTransactions}=require('../src/auth');let now=0;const t=new LoginTransactions({now:()=>now,ttlMs:100});const a=t.begin();assert.throws(()=>t.consume(a.state,'wrong'),/Invalid/);assert.strictEqual(t.consume(a.state,a.binding).nonce,a.nonce);assert.throws(()=>t.consume(a.state,a.binding),/Invalid/);const b=t.begin();now=101;assert.throws(()=>t.consume(b.state,b.binding),/expired/);};

exports['token verification checks signature issuer audience expiry and nonce'] = async()=>{const jose=require('jose'),{TokenVerifier}=require('../src/auth');const {privateKey,publicKey}=await jose.generateKeyPair('RS256');const verifier=new TokenVerifier({issuer:'https://identity.example/realms/platform',clientId:'platform',key:publicKey});const sign=(aud='platform',extra={})=>new jose.SignJWT({nonce:'nonce',preferred_username:'dev',realm_access:{roles:['developer']},...extra}).setProtectedHeader({alg:'RS256'}).setIssuer('https://identity.example/realms/platform').setAudience(aud).setSubject('u1').setExpirationTime('5m').sign(privateKey);const good=await sign();assert.strictEqual((await verifier.verify(good,'nonce')).sub,'u1');await assert.rejects(verifier.verify(await sign('wrong'),'nonce'));await assert.rejects(verifier.verify(good,'wrong'));const other=await jose.generateKeyPair('RS256');await assert.rejects(new TokenVerifier({issuer:'https://identity.example/realms/platform',clientId:'platform',key:other.publicKey}).verify(good));};

exports['template creation rejects anonymous and viewer identities'] = async()=>{const jose=require('jose'),{privateKey,publicKey}=await jose.generateKeyPair('RS256');const {createAuth}=require('../src/auth');const {request}=require('./helpers');const issuer='https://identity.example/realms/platform';const auth=createAuth({issuer,clientId:'platform',baseUrl:'http://localhost:4600',key:publicKey});const runtime=await require('../src/server').start(0,{auth,catalogFactory:async()=>{throw Error('offline')}});try{const port=runtime.server.address().port;assert.strictEqual((await request(port,'/api/templates/generate','POST',{})).status,401);const token=await new jose.SignJWT({realm_access:{roles:['viewer']}}).setProtectedHeader({alg:'RS256'}).setSubject('viewer').setIssuer(issuer).setAudience('platform').setExpirationTime('5m').sign(privateKey);assert.strictEqual((await request(port,'/api/templates/generate','POST',{}, {Authorization:'Bearer '+token})).status,403);}finally{await runtime.stop();}};

exports['logout requires the application origin and clears session cookies'] = async()=>{const {request}=require('./helpers');const runtime=await require('../src/server').start(0,{catalogFactory:async()=>{throw Error('offline')}});try{const p=runtime.server.address().port;assert.strictEqual((await request(p,'/auth/logout','POST',{}, {Origin:'https://outside.example'})).status,403);const r=await request(p,'/auth/logout','POST',{}, {Origin:'http://localhost:4600'});assert.strictEqual(r.status,200);assert(r.headers['set-cookie'].some(c=>c.includes('platform_session=;')));}finally{await runtime.stop();}};

exports['identity HTTP adapter accepts empty create responses and preserves status errors'] = async()=>{const http=require('http'),{requestJson}=require('../src/auth');const s=http.createServer((req,res)=>{res.statusCode=req.url==='/created'?201:409;res.end();});await new Promise(r=>s.listen(0,'127.0.0.1',r));try{const url='http://127.0.0.1:'+s.address().port;assert.strictEqual(await requestJson(url+'/created'),null);await assert.rejects(requestJson(url+'/conflict'),e=>e.status===409);}finally{await new Promise(r=>s.close(r));}};
