const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
function project(run){const d=fs.mkdtempSync(path.join(os.tmpdir(),'maint-')),dir=path.join(d,'api');require('../src/templates').generate({name:'orders',owner:'platform-team',language:'node'},dir);try{return run(dir)}finally{fs.rmSync(d,{recursive:true,force:true})}}

exports["maintenance DPK01"]=()=>{const {validateInput}=require('../src/templates');const base={name:'api',owner:'team',language:'node'};for(const value of ['api-', ['api'],{toString:()=> 'api'},'a'.repeat(64)])assert(validateInput({...base,name:value}).length);assert.deepStrictEqual(validateInput({...base,name:'a'.repeat(63)}),[]);assert.deepStrictEqual(validateInput({...base,name:'a'}),[])};

exports["maintenance DPK02"]=()=>{const {validateInput}=require('../src/templates');const base={name:'api',owner:'team',language:'node'};for(const port of [true,[4605],'0x1200','1e3',' 4605 ',0,65536])assert(validateInput({...base,port}).length);for(const port of [1,65535,'4605'])assert.deepStrictEqual(validateInput({...base,port}),[])};

exports["maintenance DPK03"]=()=>{const {validateCatalog}=require('../src/catalog');const bad=[{kind:'Component',metadata:{name:'api'},spec:{lifecycle:'production',owner:'component:default/api'}}];assert(validateCatalog(bad).some(x=>x.includes('Group')));const good=[{kind:'Group',metadata:{name:'team'}},{...bad[0],spec:{...bad[0].spec,owner:'group:default/team'}}];assert.deepStrictEqual(validateCatalog(good),[])};

exports["maintenance DPK04"]=()=>{const {entityRef,validateCatalog}=require('../src/catalog');const e=namespace=>({kind:'Group',metadata:{name:'team',namespace}});assert.equal(entityRef(e('payments')),'group:payments/team');assert.deepStrictEqual(validateCatalog([e('payments'),e('support')]),[]);assert(validateCatalog([e('payments'),e('payments')]).some(x=>x.includes('Duplicate')));assert(validateCatalog([e('../bad')]).some(x=>x.includes('namespace')))};

exports["maintenance DPK05"]=()=>{const {validateCatalog}=require('../src/catalog');const service={kind:'Component',metadata:{name:'web'},spec:{owner:'group:default/team',lifecycle:'production',providesApis:['missing']}};const entities=[{kind:'Group',metadata:{name:'team'}},service];assert(validateCatalog(entities).some(x=>x.includes('unknown API')));entities.push({kind:'API',metadata:{name:'api'}});service.spec.providesApis=['api'];assert.deepStrictEqual(validateCatalog(entities),[]);service.spec.consumesApis=['group:default/team'];assert(validateCatalog(entities).some(x=>x.includes('unknown API')))};

exports["maintenance DPK06"]=()=>project(dir=>{const u=require('../src/upgrades'),file=path.join(dir,'src/server.ts'),missing=path.join(path.dirname(dir),'missing');fs.unlinkSync(file);fs.symlinkSync(missing,file);assert.throws(()=>u.applyUpgrade(dir,{port:4620}),/symlink/);assert(!fs.existsSync(missing));fs.unlinkSync(file);const alias=path.join(path.dirname(dir),'alias');fs.symlinkSync(dir,alias);assert.throws(()=>u.planUpgrade(alias,{port:4620}),/symlink/);assert.deepStrictEqual(fs.readdirSync(path.dirname(dir)).sort(),['alias','api'])});

exports["maintenance DPK07"]=()=>project(dir=>{const file=path.join(dir,'.platform-template.json'),saved=path.join(path.dirname(dir),'metadata');fs.renameSync(file,saved);fs.symlinkSync(saved,file);assert.throws(()=>require('../src/upgrades').planUpgrade(dir,{port:4620}),/symlink/);fs.unlinkSync(file);fs.mkdirSync(file);assert.throws(()=>require('../src/upgrades').planUpgrade(dir,{port:4620}),/regular file/);assert(fs.existsSync(saved))});

exports["maintenance DPK08"]=()=>project(dir=>{const before=fs.readFileSync(path.join(dir,'.platform-template.json'),'utf8');assert.throws(()=>require('../src/upgrades').applyUpgrade(dir,{language:'dotnet'}),/language/);assert.strictEqual(fs.readFileSync(path.join(dir,'.platform-template.json'),'utf8'),before);assert.deepStrictEqual(fs.readdirSync(path.dirname(dir)),['api'])});

exports["maintenance DPK09"]=()=>project(dir=>{const file=path.join(dir,'src/server.ts'),before=fs.readFileSync(file),siblings=fs.readdirSync(path.dirname(dir));const result=require('../src/upgrades').applyUpgrade(dir);assert.strictEqual(result.unchanged,true);assert.strictEqual(result.backup,null);assert.deepStrictEqual(result.changes,[]);assert.deepStrictEqual(fs.readdirSync(path.dirname(dir)),siblings);assert.deepStrictEqual(fs.readFileSync(file),before);const changed=require('../src/upgrades').applyUpgrade(dir,{port:4620});assert(changed.backup);assert(changed.changes.length)});

exports["maintenance DPK10"]=()=>project(dir=>{const {managedPath}=require('../src/upgrades');assert.throws(()=>managedPath(dir,'src\\server.ts'),/Invalid managed path/);for(const name of ['src//server.ts','src/./server.ts','../outside'])assert.throws(()=>managedPath(dir,name),/Invalid managed path/);assert.strictEqual(managedPath(dir,'src/server.ts'),path.join(dir,'src/server.ts'))});

exports["maintenance DPK11"]=async()=>{const http=require('http'),s=http.createServer((_q,r)=>r.end('{"status":"ready"}'));await new Promise(r=>s.listen(0,'127.0.0.1',r));try{let result;await assert.doesNotReject(async()=>{result=await require('../src/status').probeAll([{name:'bad',url:'invalid'},{name:'good',url:'http://127.0.0.1:'+s.address().port}])});assert.deepStrictEqual(result.map(x=>x.state),['unavailable','ready']);assert.deepStrictEqual(result.map(x=>x.name),['bad','good'])}finally{await new Promise(r=>s.close(r))}};

exports["maintenance DPK12"]=async()=>{const {probe,StatusStore}=require('../src/status');for(const timeoutMs of [NaN,Infinity,-1,true,60001]){let thrown=false;try{await probe('http://127.0.0.1:1',{timeoutMs})}catch(e){thrown=/deadline/.test(e.message)}assert(thrown)}for(const ttlMs of [NaN,Infinity,-1,true,300001])assert.throws(()=>new StatusStore([],{ttlMs}),/TTL/);assert.deepStrictEqual(await new StatusStore([],{ttlMs:0}).read(),[])};

exports["maintenance DPK14"]=()=>{const {LoginTransactions}=require('../src/auth'),tx=new LoginTransactions(),t=tx.begin();assert.throws(()=>tx.consume(t.state,'é'.repeat(t.binding.length)),/Invalid login state/);assert.equal(tx.consume(t.state,t.binding).state,t.state)};

exports["maintenance DPK15"]=()=>{const tx=new (require('../src/auth').LoginTransactions)();for(const value of ['/%2foutside','/%5coutside','/catalog%0d%0aLocation:x','/%00','/%zz'])assert.throws(()=>tx.begin(value),/Invalid return path/);assert.equal(tx.begin('/catalog?filter=hello%20world').returnTo,'/catalog?filter=hello%20world')};

exports["maintenance DPK16"]=()=>{let value;assert.doesNotThrow(()=>{value=require('../src/deployment').summarize({metadata:{name:'platform-demo'},status:{health:{status:{nested:true}},sync:{status:'s'.repeat(1000)},resources:[null,7,{kind:'Service',name:'n'.repeat(1000),health:{status:{secret:true}}}]}})});assert.equal(value.health,'Unknown');assert.equal(value.sync.length,128);assert.equal(value.resources.length,1);assert.equal(value.resources[0].name.length,128);assert.equal(value.resources[0].health,null)};

exports["maintenance DPK17"]=async()=>{const {request}=require('./helpers'),runtime=await require('../src/server').start(0,{catalogFactory:async()=>{throw Error('offline')}});try{for(const method of ['GET','POST']){const r=await request(runtime.server.address().port,'/api/does-not-exist',method);assert.equal(r.status,404);assert.equal(r.body.error,'API resource not found')}assert.equal((await request(runtime.server.address().port,'/api/docs')).status,200)}finally{await runtime.stop()}};

async function generatedApi(options,fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'generated-maint-')),ts=require('typescript');try{fs.mkdirSync(path.join(dir,'dist'));for(const name of ['server','items']){const source=fs.readFileSync(path.join(__dirname,'../templates/node/src',name+'.ts'),'utf8').replace(/__NAME__/g,'sample').replace(/__PORT__/g,'4605');fs.writeFileSync(path.join(dir,'dist',name+'.js'),ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText)}const server=require(path.join(dir,'dist/server.js')).createServer(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{return await fn(server.address().port,server)}finally{await new Promise(r=>server.close(r))}}finally{fs.rmSync(dir,{recursive:true,force:true})}}

exports["maintenance DPK18"]=async()=>generatedApi({},async port=>{const {request}=require('./helpers');assert.equal((await request(port,'/items','POST',{title:'x'},{'Content-Type':'application/jsonp'})).status,415);assert.equal((await request(port,'/items','POST',{title:'x'},{'Content-Type':'application/json; charset=utf-8'})).status,201)});

exports["maintenance DPK19"]=async()=>generatedApi({maxItems:2},async port=>{const {request}=require('./helpers');for(const title of ['one','two'])assert.equal((await request(port,'/items','POST',{title})).status,201);const full=await request(port,'/items','POST',{title:'overflow'});assert.equal(full.status,503);assert.equal(full.headers['retry-after'],'60');assert.equal((await request(port,'/items')).body.length,2);assert.equal((await request(port,'/health')).status,200)});

exports["maintenance DPK20"]=()=>{const serverFile=require.resolve('../src/server'),code=`const http=require('http'),s=http.createServer();const timer=setTimeout(()=>process.exit(2),1500);s.listen(0,'127.0.0.1',async()=>{let cleaned=0;try{await require(${JSON.stringify(serverFile)}).start(s.address().port,{catalogFactory:async()=>({router:require(${JSON.stringify(require.resolve('express'))}).Router(),stop:async()=>{cleaned++}})})}catch(e){if(e.code==='EADDRINUSE'&&cleaned===1)console.log('caught and cleaned');else process.exitCode=3}finally{clearTimeout(timer);s.close()}})`;const r=require('child_process').spawnSync(process.execPath,['-e',code],{encoding:'utf8',timeout:3000});assert.equal(r.status,0,r.stderr);assert(r.stdout.includes('caught and cleaned'),r.stdout)};
