const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
function project(run){const d=fs.mkdtempSync(path.join(os.tmpdir(),'maint-')),dir=path.join(d,'api');require('../src/templates').generate({name:'orders',owner:'platform-team',language:'node'},dir);try{return run(dir)}finally{fs.rmSync(d,{recursive:true,force:true})}}

exports["maintenance DPK01"]=()=>{const {validateInput}=require('../src/templates');const base={name:'api',owner:'team',language:'node'};for(const value of ['api-', ['api'],{toString:()=> 'api'},'a'.repeat(64)])assert(validateInput({...base,name:value}).length);assert.deepStrictEqual(validateInput({...base,name:'a'.repeat(63)}),[]);assert.deepStrictEqual(validateInput({...base,name:'a'}),[])};

exports["maintenance DPK02"]=()=>{const {validateInput}=require('../src/templates');const base={name:'api',owner:'team',language:'node'};for(const port of [true,[4605],'0x1200','1e3',' 4605 ',0,65536])assert(validateInput({...base,port}).length);for(const port of [1,65535,'4605'])assert.deepStrictEqual(validateInput({...base,port}),[])};

exports["maintenance DPK03"]=()=>{const {validateCatalog}=require('../src/catalog');const bad=[{kind:'Component',metadata:{name:'api'},spec:{lifecycle:'production',owner:'component:default/api'}}];assert(validateCatalog(bad).some(x=>x.includes('Group')));const good=[{kind:'Group',metadata:{name:'team'}},{...bad[0],spec:{...bad[0].spec,owner:'group:default/team'}}];assert.deepStrictEqual(validateCatalog(good),[])};

exports["maintenance DPK04"]=()=>{const {entityRef,validateCatalog}=require('../src/catalog');const e=namespace=>({kind:'Group',metadata:{name:'team',namespace}});assert.equal(entityRef(e('payments')),'group:payments/team');assert.deepStrictEqual(validateCatalog([e('payments'),e('support')]),[]);assert(validateCatalog([e('payments'),e('payments')]).some(x=>x.includes('Duplicate')));assert(validateCatalog([e('../bad')]).some(x=>x.includes('namespace')))};

exports["maintenance DPK05"]=()=>{const {validateCatalog}=require('../src/catalog');const service={kind:'Component',metadata:{name:'web'},spec:{owner:'group:default/team',lifecycle:'production',providesApis:['missing']}};const entities=[{kind:'Group',metadata:{name:'team'}},service];assert(validateCatalog(entities).some(x=>x.includes('unknown API')));entities.push({kind:'API',metadata:{name:'api'}});service.spec.providesApis=['api'];assert.deepStrictEqual(validateCatalog(entities),[]);service.spec.consumesApis=['group:default/team'];assert(validateCatalog(entities).some(x=>x.includes('unknown API')))};

exports["maintenance DPK06"]=()=>project(dir=>{const u=require('../src/upgrades'),file=path.join(dir,'src/server.ts'),missing=path.join(path.dirname(dir),'missing');fs.unlinkSync(file);fs.symlinkSync(missing,file);assert.throws(()=>u.applyUpgrade(dir,{port:4620}),/symlink/);assert(!fs.existsSync(missing));fs.unlinkSync(file);const alias=path.join(path.dirname(dir),'alias');fs.symlinkSync(dir,alias);assert.throws(()=>u.planUpgrade(alias,{port:4620}),/symlink/);assert.deepStrictEqual(fs.readdirSync(path.dirname(dir)).sort(),['alias','api'])});

exports["maintenance DPK07"]=()=>project(dir=>{const file=path.join(dir,'.platform-template.json'),saved=path.join(path.dirname(dir),'metadata');fs.renameSync(file,saved);fs.symlinkSync(saved,file);assert.throws(()=>require('../src/upgrades').planUpgrade(dir,{port:4620}),/symlink/);fs.unlinkSync(file);fs.mkdirSync(file);assert.throws(()=>require('../src/upgrades').planUpgrade(dir,{port:4620}),/regular file/);assert(fs.existsSync(saved))});
