const assert=require('assert'),fs=require('fs'),os=require('os'),path=require('path');
function project(run){const d=fs.mkdtempSync(path.join(os.tmpdir(),'upgrade-')),target=path.join(d,'api');require('../src/templates').generate({name:'orders',owner:'platform-team',language:'node'},target);try{return run(target)}finally{fs.rmSync(d,{recursive:true,force:true})}}
exports['drift distinguishes modified missing and intact managed files'] = ()=>project(dir=>{const {drift}=require('../src/upgrades');assert(drift(dir).every(f=>f.state==='intact'));fs.appendFileSync(path.join(dir,'src/server.ts'),'// edit');fs.unlinkSync(path.join(dir,'README.md'));const result=drift(dir);assert.strictEqual(result.find(f=>f.path==='src/server.ts').state,'modified');assert.strictEqual(result.find(f=>f.path==='README.md').state,'missing');});

exports['upgrade preview detects local edits before changing generated settings'] = ()=>project(dir=>{const {planUpgrade}=require('../src/upgrades');const plan=planUpgrade(dir,{port:4620});assert(plan.changes.some(c=>c.path==='src/server.ts'));assert.deepStrictEqual(plan.conflicts,[]);fs.appendFileSync(path.join(dir,'src/server.ts'),'// local');assert(planUpgrade(dir,{port:4620}).conflicts.includes('src/server.ts'));});

exports['upgrade applies through a full backup and preserves recoverable originals'] = ()=>project(dir=>{const {applyUpgrade,drift}=require('../src/upgrades');const result=applyUpgrade(dir,{port:4620});assert(fs.readFileSync(path.join(dir,'src/server.ts'),'utf8').includes('4620'));assert(fs.existsSync(path.join(result.backup,'src/server.ts')));assert(drift(dir).every(f=>f.state==='intact'));});

exports['upgrades preserve custom files permissions and repository metadata'] = ()=>project(dir=>{fs.writeFileSync(path.join(dir,'custom.txt'),'my extension',{mode:0o600});fs.mkdirSync(path.join(dir,'.git'));fs.writeFileSync(path.join(dir,'.git','owner-marker'),'preserved');const result=require('../src/upgrades').applyUpgrade(dir,{port:4620});assert.strictEqual(fs.readFileSync(path.join(dir,'custom.txt'),'utf8'),'my extension');assert.strictEqual(fs.statSync(path.join(dir,'custom.txt')).mode&0o777,0o600);assert.strictEqual(fs.readFileSync(path.join(dir,'.git','owner-marker'),'utf8'),'preserved');assert(fs.existsSync(path.join(result.backup,'custom.txt')));});
exports['upgrades refuse symlinked managed files without touching targets'] = ()=>project(dir=>{const file=path.join(dir,'src/server.ts'),outside=path.join(path.dirname(dir),'outside');fs.writeFileSync(outside,'private');fs.unlinkSync(file);fs.symlinkSync(outside,file);assert.throws(()=>require('../src/upgrades').applyUpgrade(dir,{port:4620}),/symlink/);assert.strictEqual(fs.readFileSync(outside,'utf8'),'private');});
